# Generated by Django 3.1.6 on 2021-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=250)),
                ('nombre', models.CharField(blank=True, max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
